id: P010527
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG13685
  title: འཇམ་མགོན་ཆོས་ཀྱི་རྒྱལ་པོ་ཙོང་ཁ་པ་ཆེན་པོའི་རྣམ་ཐར།
  author: ''
  volumes:
    651b403eca0a44c8a8a28cdc36a4ef2d:
      image_group_id: I1KG13751
      title: ''
      volume_number: 1
      total_pages: 665
