id: I40E7A7A6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T07:44:35+00:00'
last_modified: '2022-06-08T14:15:48.359155+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG13685
  title: འཇམ་མགོན་ཆོས་ཀྱི་རྒྱལ་པོ་ཙོང་ཁ་པ་ཆེན་པོའི་རྣམ་ཐར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '5050':
      image_group_id: I1KG13751
      title: ''
      total_pages: 665
      order: 1
      base_file: 5050.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
